# Generated by Django 3.1 on 2020-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_remove_postmessage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
